package com.gchoy.altimeter

val PREF_DECIMALS = "PREF_DECIMALS"
val PREF_UNITS = "PREF_UNITS"
val PREF_CALIBRATION_PRESSURE = "PREF_CALIBRATION_PRESSURE"
val PREF_CALIBRATION_TIME = "PREF_CALIBRATION_TIME"
val PREF_CURRENT_PRESSURE = "PREF_CURRENT_PRESSURE"